version: '2'
services:
    postgres:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/stager/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=stager
            - POSTGRES_PASSWORD=

    templates:
        image: templates
        ports:
            - 8081:80
