version: '2'
services:
    stager-app:
        image: stager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://stager-postgresql:5432/stager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    stager-postgresql:
        extends:
            file: postgresql.yml
            service: stager-postgresql
