version: '2'
services:
    stager-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/stager/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=stager
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
